WITH CTE AS
(
    SELECT RANK() OVER (PARTITION BY OCCUPATION ORDER BY NAME ASC) RANK,
        CASE WHEN OCCUPATION = 'DOCTOR' THEN NAME ELSE NULL END AS DOCTOR,
        CASE WHEN OCCUPATION = 'PROFESSOR' THEN NAME ELSE NULL END AS PROFESSOR,
        CASE WHEN OCCUPATION = 'SINGER' THEN NAME ELSE NULL END AS SINGER,
        CASE WHEN OCCUPATION = 'ACTOR' THEN NAME ELSE NULL END AS ACTOR
    FROM OCCUPATIONS
)
SELECT MIN(DOCTOR), MIN(PROFESSOR), MIN(SINGER), MIN(ACTOR) FROM CTE GROUP BY RANK

---

SELECT [DOCTOR], [PROFESSOR], [SINGER], [ACTOR] FROM
(
    SELECT RANK() OVER (PARTITION BY OCCUPATION ORDER BY NAME ASC) RANK, * FROM OCCUPATIONS
) AS tmp

PIVOT
(
    MIN(NAME) FOR OCCUPATION IN ([DOCTOR], [PROFESSOR], [SINGER], [ACTOR])
) AS pivot_data